### ISSUE TITLE
Can't paginate queries using $geoNear, $near, and $nearSphere

### ISSUE THREAD

**Issue by vrufine** [WebGangster/mongoose-paginate-v2#42]
**Describe the bug**
When I run a Model.paginate(query) where `query` needs to filter elements by a 2dsphere index using $geoNear (in my case), the response is an error with the message `$geoNear, $near, and $nearSphere are not allowed in this context`.

**To Reproduce**
1. Create a collection
2. Create a "2dsphere" index pointing to a model property.
3. Run the model.paginate() querying the 2dsphere property index.
4. See error `$geoNear, $near, and $nearSphere are not allowed in this context`

**Expected behavior**
Outputs documents in order of nearest to farthest from a specified point.

(check out the official documentation: https://docs.mongodb.com/manual/reference/operator/aggregation/geoNear/)

**Desktop:**
 - OS: MacOS
 - Browser Chrome 76
 - Version Mojave

**Additional context**
When using the `model.find()` method the query works fine.

**Comment by vrufine** [comment]
#43

**Comment by aravindnc** [comment]
@vrufine Update

Below are the operators that count() supports but countDocuments() does not, and the suggested replacement:

$where: $expr
$near: $geoWithin with $center
$nearSphere: $geoWithin with $centerSphere

**Comment by antoniojps** [comment]
@aravindnc Those are not a replacement.

Both the $near and $nearSphere queries return the documents from nearest to farthest while the #geoWithin does not. 

This are completely different queries and should not be seen as a replacement.

Is there anyway to use count() with this package?

**Comment by aravindnc** [comment]
@antoniojps 
This is a know issue with countDocuments(). So that is why I've excluded those in the plugin.

https://docs.mongodb.com/manual/reference/method/db.collection.countDocuments/#query-restrictions

mongoose-paginate supports this because it is using count() which is a deprecated method.

**Comment by aravindnc** [comment]
@antoniojps I'm going to add a patch to use count() if needed. Let me know if that helps.

**Comment by aravindnc** [comment]
This has been fixed, you can use **forceCountFn** as true in options if you need to use $geo queries.

**Comment by antoniojps** [comment]
@aravindnc I'm impressed, thank you very much for the open source work you do.

**Comment by Alijaaan** [comment]
After adding `forceCountFn: true`

I have this warning : 
DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use Collection.countDocuments or Collection.estimatedDocumentCount instead

**Comment by aravindnc** [comment]
@Alijaaan 
Yes actually geo queries are not supported. Please read below.

https://github.com/aravindnc/mongoose-paginate-v2#note
https://docs.mongodb.com/manual/reference/method/db.collection.countDocuments/#query-restrictions
https://docs.mongodb.com/manual/reference/method/db.collection.estimatedDocumentCount/#mechanics

Otherwise you can change your query to aggregate pipeline and try using mongoose-aggregate-paginate-v2 package which should work.

**Comment by Anhunghezo** [comment]
> mongoose-aggregate-paginate-v2

I try forceCountFn: true in options but it still not working.
It does not even warn.

Is there any way to fix this problem yet?
